### ISSUE TITLE
Prediction Tile night mode text in dark mode is black

### ISSUE THREAD

**Issue by StanfordLin** [fysoul17/google_maps_place_picker#1]
Hard to see the text on grey background. 

Also, the dropdown pin is white in dark mode and it's hard to see on the regular map.

Just removing the color property on the prediction tiles would fix it.

Thx!

**Comment by fysoul17** [comment]
For the Text issue, although the text is automatically shown as white with a grey background in dark mode, 

1. I modified prediction tile colors to be matched to the Card color of the Theme Data (Theme.of(context).cardColor).

2. You can edit Tile(FloatingCard)'s color by applying theme on MaterialApp()
```dart
theme: ThemeData.dark().copyWith(
        cardColor: Colors.grey,                  // Background color of the FloatingCard
        buttonTheme: ButtonThemeData(
          buttonColor: Colors.yellow,            // Select here's button color
          textTheme: ButtonTextTheme.primary,    // Applying this will automatically change text color based on buttonColor. (Button color is dark ? white / is light ? black)
        ),
        textTheme: TextTheme(
          body1: TextStyle(color: Colors.white), // This will change the text color of FloatingCard
        ),
      ),
```

Just the color text of "select here" button is fixed to white now. I will fix this in the next update which will be updated today.

Regarding the pin and back button, 

1. The pin will default to be always [red] from now. You can still customize your pin using pinBuilder if you don't like default style ;).
