### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by LuisGrt** [fysoul17/google_maps_place_picker#101]
I am currently migrating my app to null-safety and I am unable to upgrade several packages because this depends on google_maps_flutter, Http and Provider. It is holding back several other libraries.

Is there any plans to support null-safety? I would like to know if I have to migrate to another package.

**Comment by lailai0715** [comment]
Looking forward to get a null-safety upgrade to this package too

**Comment by LuisGrt** [comment]
Hello @lailai0715, I migrated myself the package and I'll be submitting a pull request soon.

**Comment by fysoul17** [comment]
Now it is supported with pre-released version 2.0.0-nullsafety.0.
