### ISSUE TITLE
Dependency failed with new version

### ISSUE THREAD

**Issue by ctykaya** [fysoul17/google_maps_place_picker#105]
**Describe the bug**
Because google_maps_place_picker >=1.0.1 depends on google_maps_flutter ^1.0.6 and new_project depends on google_maps_flutter ^2.0.1, google_maps_place_picker >=1.0.1 is forbidden.
So, because new_project depends on google_maps_place_picker ^1.0.1, version solving failed.
pub get failed (1; So, because new_project depends on google_maps_place_picker ^1.0.1, version solving failed.)

pubspec.yaml
name: new_project
description: A new Flutter application.
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.7
  scroll_snap_list: ^0.6.0
  intl: ^0.17.0
  multi_select_flutter: ^3.1.6
  flutter_spinkit: "^4.1.2"
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.0
  image_picker: ^0.7.2
  date_format: ^1.0.9
  fluttertoast: ^7.1.8
  provider: ^4.0.5
  google_maps_place_picker: ^1.0.1
  get_it: ^1.0.3+2
  cached_network_image: any
  date_time_format: ^1.1.1+1
  url_launcher: ^6.0.2
  mask_text_input_formatter: ^1.0.6
  scrollable_positioned_list: ^0.1.9
  flutter_slidable: ^0.5.7
  photo_view: ^0.10.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/kafalar/
    - datalar/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-BoldItalic.ttf
          style: italic
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf

**Flutter Doctor -v**
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.6 19G73 darwin-x64, locale tr-TR)
    • Flutter version 2.0.0 at /Users/cagataykaya/Developer/flutter
    • Framework revision 60bd88df91 (18 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cagataykaya/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.6 19G73 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Additional context**

Is there any plan to upgrade the version ?

**Comment by fysoul17** [comment]
try with pre-released version (2.0.0-nullsafety.0) please
