### ISSUE TITLE
an example of how to use autocompleteComponents

### ISSUE THREAD

**Issue by Xoshbin** [fysoul17/google_maps_place_picker#111]
Hi, Can anyone please give an example of how to use autocompleteComponents. Thank you
```
PlacePicker(
      autocompleteComponents: [],
```

I want to restrict the placePicker to an area or a city if possible?!

**Comment by fysoul17** [comment]
https://developers.google.com/maps/documentation/places/web-service/autocomplete

**Comment by zopagaduanjr** [comment]
Component class isn't automatically detected by my Android Studio, The suggested quick fix presented to me was to create your own Component Class. 

Here's an example of autocompleteComponents by importing 'package:google_maps_webservice/places.dart'

```
import 'package:google_maps_webservice/places.dart' as google_maps_api;

PlacePicker(
    apiKey: APIKeys.apiKey,   // Put YOUR OWN KEY here.
    autocompleteComponents: [
        google_maps_api.Component("country", "fr") //restrict search results to France
    ],
    onPlacePicked: (result) { 
        print(result.address); 
        Navigator.of(context).pop();
    },
    initialPosition: HomePage.kInitialPosition,
        useCurrentLocation: true,
    ),
```
Component Class [documentation](https://pub.dev/documentation/google_maps_webservice/latest/google_maps_webservice.timezone/Component-class.html).
