### ISSUE TITLE
We don't want to search location again if camera location is changed by zooming in/out

### ISSUE THREAD

**Issue by giaur500** [fysoul17/google_maps_place_picker#120]
https://github.com/fysoul17/google_maps_place_picker/blob/d79c3a3920ea3faa956229cce1a22f11e2941798/lib/src/google_map_place_picker.dart#L84

Actually, we want to. With current approach, please test:
- show place picker with autoselect current location
- move pin without zooming in/out: new location picked up correctly
- press my location button. Map will zoom to current position, but new location won't be searched, because zoom has been changed. So result will be new pin position with invalid address selected

To solve that, need to remove restriction or better - determine if pin position has been changed while zooming or not. Or another approach - determine zoom reason, if it's after my location tap, search location again.

**Comment by fysoul17** [comment]
Have you tried with parameter [forceSearchOnZoomChanged] ?

**Comment by giaur500** [comment]
I was blind, of course you are right. However, that could be good improvement to search only when pin position changed. That's actually not related to zoom change, most important is to determine if pin position changed or not.

**Comment by martin-braun** [comment]
@giaur500 You are right, I made a PR to change the behavior in a sense that it will always search when the location has changed, no matter what.
