### ISSUE TITLE
Please update to latest version of provider

### ISSUE THREAD

**Issue by eliezerp3** [fysoul17/google_maps_place_picker#122]
First of all, I would like to thank those involved in the creation of this package. It looks great!

I tried installing it but i am getting this error.
ERR : Because google_maps_place_picker <2.0.0-nullsafety.0 depends on provider ^4.0.1 and [my project] depends on provider ^5.0.0, google_maps_place_picker <2.0.0-nullsafety.0 is forbidden.

Any way you guys can update to the latest version of provider?

**Comment by fysoul17** [comment]
You can try with [dependency-overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).

dependency_overrides:
    provider: ^5.0.0

**Comment by eliper3** [comment]
> You can try with [dependency-overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
> 
> dependency_overrides:
> provider: ^5.0.0

Thank you. Do you know if there were any breaking changes in provider 5.0.0 that will break this package?

**Comment by fysoul17** [comment]
1) You might want to have a look at the provider package's document to see what has been changed. It won't affect as long as compiling your project fails.

2) Pin always stays at the center of the map. This means if you set the initial position, the pin will point to the location you set with [initialPosition](https://github.com/fysoul17/google_maps_place_picker#placepicker) option.
