### ISSUE TITLE
Current Location button moves the map but does not update address on first attempt. It works on second attempt, though.

### ISSUE THREAD

**Issue by jawadashraf** [fysoul17/google_maps_place_picker#127]
**Describe the bug**
Current Location button moves the map but does not update address on first attempt. It works on second attempt, though.

**To Reproduce**
Please see the video
[https://drive.google.com/file/d/1CQGmbIKc3IGf6em9HiTDmZFhvKZMPShx/view?usp=sharing](https://drive.google.com/file/d/1CQGmbIKc3IGf6em9HiTDmZFhvKZMPShx/view?usp=sharing)

**Expected behavior**
Current location button should update the address on first click

**Comment by venkata-reddy-boya** [comment]
@jawadashraf  use **selectInitialPosition: true**

**Comment by jawadashraf** [comment]
> @jawadashraf use **selectInitialPosition: true**

Thanks for the response. Appreciate it.
