### ISSUE TITLE
the _buildSelectionDetails() returns always the name of picked place in English

### ISSUE THREAD

**Issue by AITechNassim** [fysoul17/google_maps_place_picker#13]
Hi @fysoul17 
First, thanks for your time to develop this package. I really appreciate.

When I select a place in the autocomplete, the function _buildSelectionDetails() always return the name of the place in English. Even if the place in the autocomplete shows in a language different from English. However, the place is still the same.

[This picture shows the search result.](https://drive.google.com/file/d/1S_YOm-qb3j82ub8Y1izy8OMDsaJWVSaH/view?usp=sharing)

[This picture shows the results after selecting an item from the autocomplete](https://drive.google.com/file/d/1S_YOm-qb3j82ub8Y1izy8OMDsaJWVSaH/view?usp=sharing)

I tried to find a solution but couldn't do it.

**Comment by fysoul17** [comment]
Hi @AITechNassim 

Please **Update to version 0.7.1** and try with the attribute 'autocompleteLanguage'.
Language codes are [here](https://developers.google.com/maps/faq#languagesupport).

**Comment by AITechNassim** [comment]
@fysoul17 . It works perfectly. Thanks a lot for the enhancement.
