### ISSUE TITLE
CircularProgressIndicator

### ISSUE THREAD

**Issue by SakhileMamba** [fysoul17/google_maps_place_picker#145]
I have noticed that the CircularProgressIndicator does not work when the pinpoint marker has been moved to a new location and the SearchState is searching, as the details of the new location are being searched. the floating card shows the details of the previous location instead of the CircularProgressIndicator. 

The same is true whilst the internet connection is turned off, instead of a progress indicator or an error message indicating that the internet connection is unavailable, the old location details are shown.

However, if the custom selectedPlaceWidgetBuilder parameter is defined, the circular progress indicator is shown correctly whilst the search state is searching or whilst an internet connection is unavailable.

**Comment by martin-braun** [comment]
> I have noticed that the CircularProgressIndicator does not work when the pinpoint marker has been moved to a new location and the SearchState is searching, as the details of the new location are being searched. the floating card shows the details of the previous location instead of the CircularProgressIndicator.

So to speak, when the internet connection is slow and you move the pin while it was still searching for the old position, it will display the old and not the new position, right?

**Comment by SakhileMamba** [comment]
I think it works ok actually.

**Comment by martin-braun** [comment]
Then you should close this issue, @SakhileMamba :)
