### ISSUE TITLE
Facing UI issues while changing Orientation.

### ISSUE THREAD

**Issue by TharaniP** [fysoul17/google_maps_place_picker#15]
Hi Fysoul17,
   Thanks for implementing this package. Its really helpful.
   
    After searching the places, if i change the orientation of my device, then Suggestion list and Select here ui are not aligned according to the orientation.

1. Search place, then suggestion list will be appear.
2. Change orientation
3. See the the screen

Expected behavior:
After getting the search results, If i change the orientation, all ui components should get aligned according to the orientation.

Thanks in advance.

**Comment by fysoul17** [comment]
Hi @TharaniP.

Please update to the new version (0.8.0). Thanks for the report.

**Comment by TharaniP** [comment]
Hi fysolu17,
   Thanks for the update. But still ui alignment and overlapping issue exist.

  Steps to reproduce:
  **Portrait to Landscape issue:**
  1. Search some place in portrait.
  2. Change the orientation to landscape. 
  3. See the place suggestion list UI. 

  ** Landscape to Portrait issue:**
  1. Search some place in landscape.
  2. Change the orientation to portrait. 
  3. See the search bar and place suggestion list UI are getting overlapped.

**Comment by fysoul17** [comment]
Thanks for the update @TharaniP,

I could reproduce the issue and it is fixed on version 0.8.1. 
Please update to the new version when it gets uploaded to pub.dev.
