### ISSUE TITLE
GPS off, Map not loading

### ISSUE THREAD

**Issue by nhtlquan** [fysoul17/google_maps_place_picker#16]
when I turn off GPS, map not show! Please fix it!

**Comment by fysoul17** [comment]
Hi @nhtlquan 

I have added isLocationServiceEnabled checking logic where we use geolocator.
Please update to version 0.8.1 and try it again.

If it still does not work, follow the below steps.
1. Set 'forceAndroidLocationManager' to true and check if works.
2. If not, you need to use 3rd party packages that checks whether the device enabled location service (GPS). Then, when the location service is off, set 'useCurrentLocation' to false. This will ignore using geolocator functions.

**Comment by fysoul17** [comment]
Please update to 0.9.0 version as there is a critical bug on 0.81 version.

Also, closing this issue as there are no updates regarding the issue.

Please re-open if further talk needed.
