### ISSUE TITLE
how to solve this issue

### ISSUE THREAD

**Issue by vipul8815** [fysoul17/google_maps_place_picker#22]
**Describe the bug**
V/ActivityThread( 1814): scheduleReceiver info = ActivityInfo{e43c398 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.ionicfirebaseapp.groceryapp cmp=com.ionicfirebaseapp.groceryapp/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 98733726
I/eapp.groceryap( 1814): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/legacy/content/WakefulBroadcastReceiver;
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/eapp.groceryap( 1814):   at android.content.BroadcastReceiver android.app.AppComponentFactory.instantiateReceiver(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:84)
I/eapp.groceryap( 1814):   at android.content.BroadcastReceiver androidx.core.app.CoreComponentFactory.instantiateReceiver(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:60)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.handleReceiver(android.app.ActivityThread$ReceiverData) (ActivityThread.java:3645)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.access$1300(android.app.ActivityThread, android.app.ActivityThread$ReceiverData) (ActivityThread.java:224)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1855)
I/eapp.groceryap( 1814):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)       
I/eapp.groceryap( 1814):   at void android.os.Looper.loop() (Looper.java:226)                                      
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7191)  
I/eapp.groceryap( 1814):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/eapp.groceryap( 1814):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:499)
I/eapp.groceryap( 1814):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:942)
I/eapp.groceryap( 1814): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.legacy.content.WakefulBroadcastReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/lib/arm64, /data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/eapp.groceryap( 1814):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/eapp.groceryap( 1814):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/eapp.groceryap( 1814):   at android.content.BroadcastReceiver android.app.AppComponentFactory.instantiateReceiver(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:84)
I/eapp.groceryap( 1814):   at android.content.BroadcastReceiver androidx.core.app.CoreComponentFactory.instantiateReceiver(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:60)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.handleReceiver(android.app.ActivityThread$ReceiverData) (ActivityThread.java:3645)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.access$1300(android.app.ActivityThread, android.app.ActivityThread$ReceiverData) (ActivityThread.java:224)
I/eapp.groceryap( 1814):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1855)
I/eapp.groceryap( 1814):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)       
I/eapp.groceryap( 1814):   at void android.os.Looper.loop() (Looper.java:226)                                      
I/eapp.groceryap( 1814):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7191)  
I/eapp.groceryap( 1814):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/eapp.groceryap( 1814):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:499)
I/eapp.groceryap( 1814):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:942)
I/eapp.groceryap( 1814):                                                                                           
D/AndroidRuntime( 1814): Shutting down VM                                                                          
E/AndroidRuntime( 1814): FATAL EXCEPTION: main                                                                     
E/AndroidRuntime( 1814): Process: com.ionicfirebaseapp.groceryapp, PID: 1814                                       
E/AndroidRuntime( 1814): java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/lib/arm64, /data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 1814):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3652)             
E/AndroidRuntime( 1814):        at android.app.ActivityThread.access$1300(ActivityThread.java:224)                 
E/AndroidRuntime( 1814):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)            
E/AndroidRuntime( 1814):        at android.os.Handler.dispatchMessage(Handler.java:106)                            
E/AndroidRuntime( 1814):        at android.os.Looper.loop(Looper.java:226)                                         
E/AndroidRuntime( 1814):        at android.app.ActivityThread.main(ActivityThread.java:7191)                       
E/AndroidRuntime( 1814):        at java.lang.reflect.Method.invoke(Native Method)                                  
E/AndroidRuntime( 1814):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
E/AndroidRuntime( 1814):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)                    
E/AndroidRuntime( 1814): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/lib/arm64, /data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 1814):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)         
E/AndroidRuntime( 1814):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)                           
E/AndroidRuntime( 1814):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                           
E/AndroidRuntime( 1814):        at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:84)
E/AndroidRuntime( 1814):        at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
E/AndroidRuntime( 1814):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3645)             
E/AndroidRuntime( 1814):        ... 8 more                                                                         
E/AndroidRuntime( 1814):        Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/legacy/content/WakefulBroadcastReceiver;
E/AndroidRuntime( 1814):                at java.lang.VMClassLoader.findLoadedClass(Native Method)                  
E/AndroidRuntime( 1814):                at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)             
E/AndroidRuntime( 1814):                at java.lang.ClassLoader.loadClass(ClassLoader.java:363)                   
E/AndroidRuntime( 1814):                ... 12 more                                                                
E/AndroidRuntime( 1814):        Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.legacy.content.WakefulBroadcastReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/lib/arm64, /data/app/com.ionicfirebaseapp.groceryapp-Axoo6StC-lAMitiO6XOi6Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 1814):                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134) 
E/AndroidRuntime( 1814):                at java.lang.ClassLoader.loadClass(ClassLoader.java:379)                   
E/AndroidRuntime( 1814):                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                   
E/AndroidRuntime( 1814):                ... 15 more                                                                
I/Process ( 1814): Sending signal. PID: 1814 SIG: 9                                                                
Lost connection to device.                                                                                         
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:43197/Ijee1eqZ1uY=/

**Comment by fysoul17** [comment]
It seems like Firebase issue.

Closing the issue as it is not related to the package.
