### ISSUE TITLE
No way to remove back button 

### ISSUE THREAD

**Issue by suthura** [fysoul17/google_maps_place_picker#23]
I have added this plugin on a part of a big screen and it works great.

In my case I want to remove the back button on left top 

Is there anyway to do this.

Thanks.

**Comment by fysoul17** [comment]
Hi, @suthura 

Please update to version 0.9.2 and set 'automaticallyImplyAppBarLeading' to false.

Thanks

**Comment by suthura** [comment]
@fysoul17 Done. Thanks genius ♥♥

**Comment by fysoul17** [comment]
Closing as the issue has been solved.
