### ISSUE TITLE
How to restrict the map and address search to just land and avoid any sea or river area?

### ISSUE THREAD

**Issue by newbieflutter** [fysoul17/google_maps_place_picker#24]
Hi,
    How to restrict the area of geocoding to just land area and avoid doing it for sea or river where there is no possible inhabitant ?

**Comment by fysoul17** [comment]
I believe that feature is not provided by google map.
Please refer to Google Map API document.

**Comment by newbieflutter** [comment]
Hi Fysoul,
                  In fact I have read the Google Map Api and did some test in the function with the following for loops. Some links suggest to look for natural type but it does not work. I guess google also cant really give exact details on this level. We have to survive with their approximation.

for(var t=0; t<result.types.length; t++){
                              print("tyye"+result.types[t].toString());
                            }
                            for(var a=0; a<result.addressComponents.length; a++){
                              print("address componenet "+result.addressComponents[a].toJson().toString());
                            }

**Comment by fysoul17** [comment]
Closing as there is no further issue with this.

**Comment by newbieflutter** [comment]
Hi,
     Ok no issue thank you for your help.
