### ISSUE TITLE
Map opening is very slow on iOS device, why it is?

### ISSUE THREAD

**Issue by jasprit** [fysoul17/google_maps_place_picker#26]
When we open map on iOS. it took around more than 30 sec to initialize the first view

**Comment by fysoul17** [comment]
I am not sure what is the problem based on the information what you provided.
Can you provide more information, please?

Such as, 

Parameter settings.
flutter doctor -v.
etc.

Or can you try with another device/simulator on other mac if the same issue happens?
Also with different internet connection condition.
 
It only takes less than 2~3 seconds on my side, which works the same as android.

**Comment by fysoul17** [comment]
Closing as there is no further update.
Feel free to update any issue to re-open it.

**Comment by sanu-krishnan** [comment]
Facing the same issue on physical iOS devices. Loads faster (1-2 seconds) in simulator, but takes too long in real devices(10-20 seconds)

Version : `google_maps_place_picker: ^2.1.0-nullsafety.3.`  (tried older versions as well)
Flutter version : `2.5.1`

Code:
```
child: PlacePicker(
        apiKey: AppConstants.gmapsApiKey,
        initialPosition: LatLng(
          _pickedLocation?.lat ?? _initialPosition.latitude,
          _pickedLocation?.lng ?? _initialPosition.longitude,
        ),
        useCurrentLocation: true,
        selectInitialPosition: true,
        usePlaceDetailSearch: true,
        autocompleteLanguage: translation.isArabic ? "ar" : "en",
        autocompleteTypes: const [],
        autocompleteComponents: [
          geocoding.Component(geocoding.Component.country, "kw")
        ],
        hintText: translation.of('customer.search_address'),
        selectedPlaceWidgetBuilder:
            (_, selectedPlace, state, isSearchBarFocused) {
          debugPrint(
            "state: $state, isSearchBarFocused: $isSearchBarFocused",
          );

          if (isSearchBarFocused) {
            return Container();
          } else {
            return _buildBottomFloatingCard(
              state,
              selectedPlace,
              context,
            );
          }
        },
      ),
```

**Comment by gsoykan** [comment]
https://github.com/fysoul17/google_maps_place_picker/issues/43#issuecomment-1049752540
