### ISSUE TITLE
Restrict to defined area

### ISSUE THREAD

**Issue by giaur500** [fysoul17/google_maps_place_picker#28]
I have city area defined as geojson. I need to restrict available area to my city only and show message when user tries to pick address outside city area. City boundary should also be visible on map to get user to know about suppoeted area.

My proposal:
- add possibility to pass area geojson
- parameters to pass: draw boundary or not + line parameters
- event to indicate user tried to select invalid location

Might be useful: https://pub.dev/packages/geojson

**Comment by fysoul17** [comment]
Hi, 

I have no idea how to implement the package you suggested. City boundary is also not supported by google map.

In addition, your usecase is a very case-specific task and thus I suggest you to fork the project and implement on your end. You can also implement your forked repo into your project using pubspec.yaml.

I am sorry that I cloud not help you with your case.

**Comment by fysoul17** [comment]
A closed issue you might want to see [here](https://github.com/fysoul17/google_maps_place_picker/issues/5).

**Comment by giaur500** [comment]
Actually, implementation is pretty easy in my opinion. All you need is to draw geojson and when user pick location, check whenever latitude/longitude is inside polygon (from geojson) or not. That has nothing to do with Google Map, only geojson feature parsing.
To be more specific I have boundary geojson by myself, as string, only need to draw it and deternine if chosen location is inside polygon or not.

Well, that may look as case specific, but still, you should consider some kind of restrictions allowed area.

**Comment by giaur500** [comment]
I have managed to fork it and add following functionalities:
- draw city boundaries (geojson passed as optional named param)
- switch to enable/disable to restrict allowed location, 
- if not allowed, user is not able to select invalid location and information message is displayed instead

`geojson_vi` and `geodesy` libraries have been used to parse/draw geojson and determine if selected location is inside allowed area or not. 

I think I can create PR, but my fork is based on older version
