### ISSUE TITLE
Autocomplete not disposing of after exiting. 

### ISSUE THREAD

**Issue by StanfordLin** [fysoul17/google_maps_place_picker#3]
**Describe the bug**

**To Reproduce**
1. Type something in the search bar
2. Press back button while there are still items that are displayed from autocomplete

**Expected behavior**
The autocompleted listtiles should be removed upon exit of the screen

**Screenshots**
![IMG_0436](https://user-images.githubusercontent.com/16379094/73320779-5362d380-41f5-11ea-9137-69ea3330657a.PNG)
![IMG_0437](https://user-images.githubusercontent.com/16379094/73320911-ba808800-41f5-11ea-8d62-70b74ba7a34d.PNG)

**Flutter Doctor -v**

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by fysoul17** [comment]
Thanks for the report. Will be fixed soon.

**Comment by fysoul17** [comment]
Please update to version 0.4.0.
