### ISSUE TITLE
hii... i have showing following error

### ISSUE THREAD

**Issue by afsalkly** [fysoul17/google_maps_place_picker#31]
Camera Location Search Error: You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

I enabled billinig account. still the problem showing

**Comment by fysoul17** [comment]
Hi,

Please follow [google_map_flutter](https://pub.dev/packages/google_maps_flutter) package to set up for Google API Key.

## Getting Started

* Get an API key at <https://cloud.google.com/maps-platform/>.

* Enable Google Map SDK for each platform.
  * Go to [Google Developers Console](https://console.cloud.google.com/).
  * Choose the project that you want to enable Google Maps on.
  * Select the navigation menu and then select "Google Maps".
  * Select "APIs" under the Google Maps menu.
  * To enable Google Maps for Android, select "Maps SDK for Android" in the "Additional APIs" section, then select "ENABLE".
  * To enable Google Maps for iOS, select "Maps SDK for iOS" in the "Additional APIs" section, then select "ENABLE".
  * Make sure the APIs you enabled are under the "Enabled APIs" section.

* You can also find detailed steps to get started with Google Maps Platform [here](https://developers.google.com/maps/gmp-get-started).

**Comment by edwin-alvarez** [comment]
I'm having the same problem, all looks enable from google side.

![image](https://user-images.githubusercontent.com/5774873/90316665-78403f00-ded8-11ea-8778-19e07a740b33.png)

**Comment by fysoul17** [comment]
@edwin-alvarez Thanks for sharing information ;)
