### ISSUE TITLE
Need way to change the text in the button

### ISSUE THREAD

**Issue by Katekko** [fysoul17/google_maps_place_picker#32]
Very nice lib, congratz

I have some questions:

Is there any way to change the "SELECT HERE" to another text?

You can show us how the billing will work with your lib? How many request it does?

The region parameter don't work. 
![image](https://user-images.githubusercontent.com/13632735/80749264-8f5f4a80-8afc-11ea-8c16-a7d3ceb44ca2.png)

You need pass to the map url my region. I think you are not passing by

**Comment by fysoul17** [comment]
Hi, @Katekko 

1. You can customize "select here" including whole floating card stuff as documented [here](https://github.com/fysoul17/google_maps_place_picker#customizing-picked-place-visualisation).

2. The primary goal is to reduce google map API calls as much as I can. It will consume 1 call per each functionality. (Autocomplete search, get a place by camera movement, etc). See [here](https://cloud.google.com/maps-platform/pricing) for google API pricing.

3. Find our which region code you can use [here](https://developers.google.com/maps/faq#languagesupport).

**Comment by Katekko** [comment]
Nice... All fine.

But about the region, I guess you are talking about languages, it's a bit diferente from region.

![image](https://user-images.githubusercontent.com/13632735/80814073-9724fa80-8ba1-11ea-9346-c0eb38d1a60c.png)

For example, when I select the region BR, the final "Brazil" on search will be supress.

**Comment by fysoul17** [comment]
There is 'autocompleteLanguage' parameter you can pass in. 
More information on the [ReadMe](https://github.com/fysoul17/google_maps_place_picker#placepicker).

**Comment by fysoul17** [comment]
Closing as there is no further update.
