### ISSUE TITLE
can't get the selected place

### ISSUE THREAD

**Issue by walide67** [fysoul17/google_maps_place_picker#33]
when i positioning on my place the "select here" button not shown the circulprogressIndicator apear for a few second and hidden 
the same issue for the search

**Comment by lucasmaffazioli** [comment]
> when i positioning on my place the "select here" button not shown the circulprogressIndicator apear for a few second and hidden
> the same issue for the search

Check your debug. For me it was the wrong API key. Also, to help the developer, post your code and debug log

**Comment by fysoul17** [comment]
Closing as there is no further update.
