### ISSUE TITLE
Camera position dont update if searched for more than one time

### ISSUE THREAD

**Issue by ricardochen** [fysoul17/google_maps_place_picker#35]
**Describe the bug**
If a place is searched and clicked for a second time, the map camera always goes to the first location (current location)

**To Reproduce**
1) useCurrentLocation: true,  (location A)
2) Search for location B
3) Search for location C
4) Search for location B again
5) instead of showing location B it shows location A

**Expected behavior**
Show the correct location after search

**Flutter Doctor -v**
[✓] Flutter (Channel master, 1.18.0-11.0.pre, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.18.0-11.0.pre at /Users/ricardochen/flutter/flutter
    • Framework revision 8568eda15b (4 days ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

**Comment by fysoul17** [comment]
Hi, @ricardochen 

I think this is the same issue as your last post. Please refer to #30  if you are using MediaQuery.

**Comment by ricardochen** [comment]
Yep, same issue thanks.

**Comment by fysoul17** [comment]
No problem. 

Closing as the issue has been resolved.
