### ISSUE TITLE
Show map in an existing page instead of pushing into new page

### ISSUE THREAD

**Issue by MuhammedAbduRafi** [fysoul17/google_maps_place_picker#37]
Hi,
Is there any way I can show the map in a container instead of button click and pushing into new page?

**Comment by fysoul17** [comment]
Hi @MuhammedAbduRafi .

Simply put as a child of the Widget.

**Comment by MuhammedAbduRafi** [comment]
@fysoul17 Actually, I already tried it like that and it wasn't working. but now it's worked after put it as a child of `Expanded` widget.

Anyway, Thanks :)
