### ISSUE TITLE
Remove optional data which is additionally charged by Google Maps

### ISSUE THREAD

**Issue by SchnMar** [fysoul17/google_maps_place_picker#42]
**Is your feature request related to a problem? Please describe.**
I just checked my billing by google maps and found additional charges for using Contact data and places details. This data is charged if you request it from google maps, but you can optionally remove it from the request. I don't need it for my app functionality and asaik the widget doesn't need it either.

The usePlaceDetailSearch parameter of the widget does add additional data, but parts of that data is free and parts of it at an additional charge. Can you provide specific parameters matching the different api categories of google maps so it is possible to better customize the widget to individual needs?

Thank you!

**Comment by fysoul17** [comment]
Hi, 
The history of 'usePlaceDetailSearch' can be found here #4 .

Anyway, I understand that using contact data causes additional charge. I will have a look later on if I can make it optional. 

In the meantime, as I have other plenty of works to do for the living, feel free to make pull request if you could provide the feature.

**Comment by fysoul17** [comment]
Closing as there is no further update.
