### ISSUE TITLE
how to show card on start

### ISSUE THREAD

**Issue by bilalhassanqadri** [fysoul17/google_maps_place_picker#45]
1.
i want to ask how can i show the card address when the user open map auto goes to current location but the card disappear  
2.
how can i show error message if the user dose not enable his gps location ?

**Comment by fysoul17** [comment]
Hi,

1. Set [selectInitialPosition] to true.

2. You need to use another package to 'check' whether the user enabled the GPS or not.

**Comment by bilalhassanqadri** [comment]
Thank for your answer i got the first one and that is working but when i close the keyboard card disappear again what is the solution for that

**Comment by bilalhassanqadri** [comment]
is there any way to solve the issue ? when customer close the keyboard the card disappear

**Comment by fysoul17** [comment]
Are you using MediaQuery in the PlacePicker widget? 
If so, it might be causing re-build of the map since MediaQuery forcibly rebuilds the whole widget when the keyboard is shown/hidden. 
It will be resolved if you remove MediaQuery.

**Comment by bilalhassanqadri** [comment]
if i remove the media query it will be problem for render the card on different size of devices

**Comment by bilalhassanqadri** [comment]
unfortunately this method not works for me i have remove the media query , but still card hides after close the keyboard , it dose not hide if user click on done but , it hide when user click on close down arrow button ↓

**Comment by fysoul17** [comment]
Closing as the second question is duplicated with #46.
