### ISSUE TITLE
the map dose not load for tab

### ISSUE THREAD

**Issue by bilalhassanqadri** [fysoul17/google_maps_place_picker#46]
i have tested the map dose not load on tab and only browse

**Comment by fysoul17** [comment]
Can you use the bug report template, please?
I don't quite understand what is your issue.

**Comment by bilalhassanqadri** [comment]
#### Issue description
in the app bar there is search box when i click on search box the matching string appear but i did not 

![image](https://user-images.githubusercontent.com/53060585/85585285-4d183c80-b659-11ea-8959-9e392bd9b1c1.png)

until now the application is fine but when user click on close down button see the image 

![image](https://user-images.githubusercontent.com/53060585/85585699-abddb600-b659-11ea-9964-13c05ba9a66b.png)


the card disappear

![image](https://user-images.githubusercontent.com/53060585/85585785-c57efd80-b659-11ea-8a12-6b67f52db170.png)

**Comment by bilalhassanqadri** [comment]
is the explanation is enough ? can you please tell me how to fix this or can you fix this ?

**Comment by fysoul17** [comment]
Great, now I got what your issue is.

However, hiding the card on the keyboard shown is intended. Otherwise, the card will be floating above the keyboard.
So, the answer is no. Currently, there is no way to re-display the card when the keyboard is hidden after it was shown.

**Comment by bilalhassanqadri** [comment]
Thanks for your explanation but can you tell  me how how to show the card on close also no matter the card floating above the keyboard.

**Comment by fysoul17** [comment]
If you are about to fork the project and modify on your side, you may want to have a look at _buildFloatingCard function in 'google_map_place_picker.dart' file.

**Comment by bilalhassanqadri** [comment]
Thank you for explanation can u tell
Me how can i call
The function i mean function is creating the card so what i am thinkiNg that when the keyboard close i will
Call that function again

**Comment by bilalhassanqadri** [comment]
I have also found one more issue and that zoom when. Zoom in the map the ping move but card address not get the current pin adress

**Comment by fysoul17** [comment]
You can find information about how the zoom works on [ReadMe](https://github.com/fysoul17/google_maps_place_picker).

In order to prevent unnecessary API calls, we do not count zoom change by default. 
There is an explanation about how you can unlock this feature in the document.

**Comment by fysoul17** [comment]
Closing as a zoom issue is not related to the current issue.

**Comment by bilalhassanqadri** [comment]
Can u please explain this question?

Thank you for explanation can u tell
Me how can i call
The function i mean function is creating the card so what i am thinkiNg that when the keyboard close i will
Call that function again

**Comment by fysoul17** [comment]
There is no way to achieve your goal without forking this project currently.

In order to modify the project, you need to fork this project, then modify the function that I specified.

**Comment by bilalhassanqadri** [comment]
okay thank you i will try my own 

when i use tab and run the project the map not appears and that is for tab 

![image](https://user-images.githubusercontent.com/53060585/85720840-3d0c6580-b70a-11ea-9721-2d1552afce2f.png)
