### ISSUE TITLE
pin geolocation

### ISSUE THREAD

**Issue by ChristianAdrian** [fysoul17/google_maps_place_picker#53]
I'm currently using this package for a food ordering app and is comparing the result to a polygon if its withing the area but I'm currently experiencing a problem the geolocation fetched is from the place result is it possible that the returns geolocation will be by the set pin instead of the fetech location result. sometimes the pin and the fetch location does not match.

**Comment by fysoul17** [comment]
Can you provide more information, please? 
Use cases, reproduce scenarios, or screenshots that I can found out what exactly the issue is? ;)

**Comment by ChristianAdrian** [comment]
in some cases when the pin does not have an address the result of the places API returns the nearest available one which in some cases is far from the pin selected by the user. I'm using this package along with a map polygon to compare  the pin if it exists within some areas in our database. I already raised an issue with the maptoolkit package because I taught It was that package that was having some problem. https://github.com/kb0/maps_toolkit/issues/4 this is the link. After it I tried discovered that it was with the places api that is having some issue.

**Comment by fysoul17** [comment]
Okay. Unfortunately, it is not possible and has no plane to provide geolocation instead of the result from place API. :( Sorry. 

The goal of the package is to provide a place data that is coming from google place API, and thus the only way to manipulate the result is by using some parameters for the Google Place API.
