### ISSUE TITLE
Search bar is on top of optional buttons

### ISSUE THREAD

**Issue by emmett-deen** [fysoul17/google_maps_place_picker#6]
**Describe the bug**
The search bar is on top of the map type and my location buttons while showing the place picker.

**Expected behavior**
Needs padding to push the buttons down

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-16 at 15 19 11](https://user-images.githubusercontent.com/7634149/74612057-cca46680-50cf-11ea-9d15-7dc184ba9e0f.png)

**Comment by fysoul17** [comment]
Thanks for reporting.

The bug has been fixed. Please update to version 0.6.2.
