### ISSUE TITLE
Question: Pricing

### ISSUE THREAD

**Issue by edwin-alvarez** [fysoul17/google_maps_place_picker#60]
I'm a bit confused, when I read the pricing in google web, it looks like auto-complete /address suggestion price is $17 / 1000 request.

https://cloud.google.com/maps-platform/pricing

Can someone provide details about what is the billable part of enabling this component?

**Comment by fysoul17** [comment]
The package uses Places API, Geocoding API and Maps API. 
So it will be charged for first two APIs as Maps API is free.

Below is a sample snapshot of the usage. 
![image](https://user-images.githubusercontent.com/7436491/90330217-71a3eb80-dfee-11ea-8183-a2809e0af543.png)

**Comment by edwin-alvarez** [comment]
How much in usd is this, I am building a open source for non-profit organization, this app will not generate any money, then trying to find out if I should enable Places API, Geocoding API. I know this question is more probably for Google than you, but maybe you can give me an idea. Thanks

**Comment by fysoul17** [comment]
It's a Korean Won. ($1 is about KRW 1200)

No problem. In regards to the request amounts, you can try the package with a new testing google account which you will have about $300 credit for free. Try few searches with example flutter app included in the package (clone this and run after setting with your google API keys) then have a look at google cloud platform console.

As the main reason I created this package is to minimize API calls, it won't charge you a lot of money unless users perform searches a lot.

You can also modify some settings to minimize API calls such as denounce times, disable API calls when the only zoom has changed or disabling searches with the pin at the center of the map etc.. Please refer to the README document for more information regarding the settings.

Hope this gives you some ideas. ;)

**Comment by fysoul17** [comment]
Closing as there is no further update.
