### ISSUE TITLE
hanging issue when app runs on few mobiles. 

### ISSUE THREAD

**Issue by MadhavDev** [fysoul17/google_maps_place_picker#63]
**Describe the bug**
Its worked in most every mobiles. But in Samsung A5  and some other mobiles it become hang when open the map screen.  So cant select location and cant do anything. Only option is "RESTARTING" the mobile. 

**To Reproduce**
1. Go to 'location picker map'

**Expected behavior**
Map is not loading completely. And cant scroll or move back

**Comment by fysoul17** [comment]
It's probably related to this #43 

Please try to play with [desiredLocationAccuracy] parameter and see if it works.

**Comment by fysoul17** [comment]
Closing as there is no further update.
