### ISSUE TITLE
Conflict with geolocator 6.0.0

### ISSUE THREAD

**Issue by faithomotoso** [fysoul17/google_maps_place_picker#66]
**Describe the bug**
I'm using the geolocator package to get the device location and I recently updated to the latest version. When I run pub get, it shows a dependency conflict because the google_maps_place_picker package is dependent on an older version making me use dependency_overrides to resolve it. The latest version of the geolocator package has breaking changes, mostly just removing the 

**To Reproduce**
add geolocator: ^6.0.0 and google_maps_place_picker: ^0.9.4 to pubspec.yaml

**Expected behavior**
No dependency conflict

**Comment by B1TB0Y01** [comment]
I have forked and improved it. It works fine now.

**Comment by fysoul17** [comment]
@faithomotoso 
I have updated to package to 0.10.0 which includes new geolocator.

@B1TB0Y01 
Thanks for the improvement. I have added to the package, so simple update to 0.10.0 then you won't need to use the forked version.

**Comment by faithomotoso** [comment]
Thank you dev
