### ISSUE TITLE
Getting user_ratings_total from PickResult

### ISSUE THREAD

**Issue by xJon** [fysoul17/google_maps_place_picker#70]
**Describe the bug**
Is it possible to get the total number of reviews for a place (`user_ratings_total`) from the PickResult?
I wasn't able to find it myself.
Thank you for a great package!

**Comment by fysoul17** [comment]
You could grab the id of the place then use other Google Map API or have a look at the [doc](https://developers.google.com/places/web-service/details) if there are some data you want.

**Comment by fysoul17** [comment]
It uses [google_map_webservice](https://pub.dev/packages/google_maps_webservice) package to fetch place detail, and thus it cannot be fetched if the data is not provided from the package.

A workaround is to grab the place id from PickResult and request to Google Map API to fetch specific data of the place. In this case, you need to use your own [selectedPlaceWidgetBuilder].

**Comment by xJon** [comment]
Do you know whether there is a reason why by default it fetches all other "Atmosphere" place details apart from `user_ratings_total`?

**Comment by fysoul17** [comment]
Sorry, I am not sure, it would be good to ask on their Github's issue. ;)

**Comment by fysoul17** [comment]
Closing as there are no further updates.
