### ISSUE TITLE
fix dependency of google_maps_flutter to 1.0.1

### ISSUE THREAD

**Issue by alexodus** [fysoul17/google_maps_place_picker#72]
google_maps_flutter is now at 1.0.1 version

**Comment by LuisGrt** [comment]
> google_maps_flutter is now at 1.0.1 version

It's now at 1.0.2. Please!

**Comment by alejandroaap** [comment]
I was currently using google maps 1.0.1 and I had to change the version to 0.5.25 + 3. Please update the version to 1.0.2 which was released on October 1st. Thank you.

**Comment by fysoul17** [comment]
I need to test with the new version of google maps (although it doesn't look there would be an issue). Until then, please use a dependency override in your pubspec.yaml.

```
dependency_overrides:
    google_maps_flutter: ^1.0.2
```

**Comment by fysoul17** [comment]
@alexodus @LuisGrt @alejandroaap 
I am happy to tell you guys that I have updated google_maps_flutter to the new version.
