### ISSUE TITLE
Searching Function not working

### ISSUE THREAD

**Issue by Reet0709** [fysoul17/google_maps_place_picker#73]
Searching Function is not working . Searching for  Location is neither showing Auto complete search bar  nor Selecting Any location . It is just Loading the search indicator to infinte.
![Screenshots](https://user-images.githubusercontent.com/63194285/95039839-83049c80-06ef-11eb-8d21-04604ed6a0e8.jpeg)

**Comment by fysoul17** [comment]
Please create with issue template.
It seems like a Google API key issue, but I cannot help you without any specific information.

**Comment by Reet0709** [comment]
> Please create with issue template.
> It seems like a Google API key issue, but I cannot help you without any specific information.

After enabling  all the following API's-

![screenshots](https://user-images.githubusercontent.com/63194285/95046732-658cfe00-0702-11eb-945b-11d3d9575def.PNG)

and then used the generated API key . But Searching function is still not functioning.  Provide your Guidance what else I need to do  to make this work.
Thanks in Advance.

**Comment by wesleyxiao** [comment]
+1 i have same issue, everything working well, only when enter address manually , marker are at the position correct, but bottom keep showing loading icon, not getting the address

![291602798504_ pic](https://user-images.githubusercontent.com/2177367/96189538-a8bf4c00-0f0e-11eb-9f09-d80074400689.jpg)

**Comment by fysoul17** [comment]
You need to put your API key

**Comment by wesleyxiao** [comment]
> You need to put your API key

Hello, I have put api key in my code, but For security purposes I didn’t put the api key on here

**Comment by fysoul17** [comment]
Was there any error in the console? I am pretty sure there are some error logs in there. 
The issue typically happens when there is a problem with the API settings.
