### ISSUE TITLE
Problem With Search Function

### ISSUE THREAD

**Issue by Reet0709** [fysoul17/google_maps_place_picker#74]
After Enabling the following API's

![screenshots](https://user-images.githubusercontent.com/63194285/95047473-c49f4280-0703-11eb-90fc-7a641dad1831.PNG)

I generated the API Key,  but still Search Function is not working ( neither Autosuggestion  are coming , nor the places searched.   It is just Loading the search indicator to infinty) .

![Screenshots](https://user-images.githubusercontent.com/63194285/95047778-4d1de300-0704-11eb-920b-711929ffca17.jpeg)

 What else I Need to do  to make it work?

**Comment by fysoul17** [comment]
Closing as it is an API related issue.
