### ISSUE TITLE
Google API Issue

### ISSUE THREAD

**Issue by Reet0709** [fysoul17/google_maps_place_picker#75]
Is it necessary to have our project with the Billing Account only ? Since  I used my API without making billing Account and the code is not working Properly. So Do I need to make a Billing Account Only? Or There is some other way .

**Comment by fysoul17** [comment]
Since this is Google related question and thus I cannot say the correct answer. But afaik, it seems like Billing Account must be set in order to use the API. Please refer to the Google Map API document.
