### ISSUE TITLE
Cannot auto picked location when search address

### ISSUE THREAD

**Issue by daivph** [fysoul17/google_maps_place_picker#86]
**Describe the bug**
Cannot auto picked location when search address

**To Reproduce**
1. Search address
2. Click on one result
3. Camera move to location, but not picked location, SearchingState always Searching

›
![Screen Shot 2020-11-28 at 16 07 21](https://user-images.githubusercontent.com/18576374/100498288-ccbfaf80-3193-11eb-8ec9-0d7a494e8538.png)

![9A62423C-891E-4492-8CF4-88D5DAFFB940](https://user-images.githubusercontent.com/18576374/100498650-3c369e80-3196-11eb-8110-2926b21c45c9.gif)

**Comment by daivph** [comment]
duplicate [https://github.com/fysoul17/google_maps_place_picker/pull/76](#76)

**Comment by shamnex** [comment]
Has this issue been fixed ?

**Comment by daivph** [comment]
> Has this issue been fixed ?

No, it's duplicate #76 and I see pull request https://github.com/fysoul17/google_maps_place_picker/pull/76
Waiting pull request approved

**Comment by shamnex** [comment]
thanks! @daivph
