### ISSUE TITLE
resizeToAvoidBottomPadding or resizeToAvoidBottomInset 

### ISSUE THREAD

**Issue by jcsena** [fysoul17/google_maps_place_picker#9]
**Is your feature request related to a problem? Please describe.**
when the keyboard appears the widget map resize.

**Describe the solution you'd like**
`resizeToAvoidBottomPadding` or `resizeToAvoidBottomInset` into `Scaffold`

**Additional context**
![](https://i.stack.imgur.com/r5o7s.png)

![](https://i.stack.imgur.com/22ixQ.png)

[When the keyboard appears](https://stackoverflow.com/questions/46551268/when-the-keyboard-appears-the-flutter-widgets-resize-how-to-prevent-this)

**Comment by fysoul17** [comment]
The requested feature has been updated to version 0.6.4.

Thanks for your contribution. ;)

**Comment by jcsena** [comment]
I confirm that in the new version(0.6.4) it works @fysoul17. thanks.
