### ISSUE TITLE
For iOS only, After Search and select place . Selected place doesn't display in "select here" box.

### ISSUE THREAD

**Issue by manpreetpatil** [fysoul17/google_maps_place_picker#95]
**Describe the bug**
For iOS only, After Search and select place . Selected place doesn't display in "select here" box. It keep showing loading.

**To Reproduce**
1. search location address
2. select the one address in suggested placed
3. Bottom select here box now showing selected search result. It keep showing loading. The issue is only for iOS. 
4. If we move map then it show the address.

**Comment by zmm2tysu** [comment]
same issue+1

**Comment by a-yarohovich** [comment]
+1

**Comment by bhavin-concetto** [comment]
after adding 

> hidePlaceDetailsWhenDraggingPin: false,

it is working for me.

**Comment by manpreetpatil** [comment]
@bhavin-concetto  Thanks, Yes it's working

**Comment by bhavin-concetto** [comment]
@manpreetpatil welcome and please close this issue.
